/**
 * Complete Tarot Card Database
 * Traditional Rider-Waite-Smith deck with comprehensive meanings
 */

import { TarotCard, TarotSuit } from '@/types/spiritual'

// ============================================================================
// MAJOR ARCANA (22 cards)
// ============================================================================

export const MAJOR_ARCANA: TarotCard[] = [
  {
    id: 'fool',
    name: 'The Fool',
    number: 0,
    arcana: 'major',
    keywords: ['new beginnings', 'innocence', 'spontaneity', 'free spirit'],
    upright_meaning: 'New beginnings, innocence, spontaneity, a free spirit. The Fool represents the beginning of a journey, taking a leap of faith, and embracing the unknown with optimism.',
    reversed_meaning: 'Holding back, recklessness, risk-taking, foolishness. When reversed, The Fool warns against being too impulsive or naive.',
    description: 'A young person stands at the edge of a cliff, ready to step into the unknown. They carry a small bag and a white rose, symbolizing purity and new beginnings.',
    symbolism: ['white rose (purity)', 'cliff (leap of faith)', 'small bag (few possessions)', 'dog (loyalty/instinct)'],
    astrological_correspondence: 'Uranus',
    numerological_value: 0,
    element: 'air',
    image_url: '/tarot/major/00-fool.jpg'
  },
  {
    id: 'magician',
    name: 'The Magician',
    number: 1,
    arcana: 'major',
    keywords: ['manifestation', 'resourcefulness', 'power', 'inspired action'],
    upright_meaning: 'Manifestation, resourcefulness, power, inspired action. The Magician represents having the tools and ability to manifest your desires into reality.',
    reversed_meaning: 'Manipulation, poor planning, untapped talents, lack of focus. When reversed, The Magician suggests misuse of power or scattered energy.',
    description: 'A figure stands before an altar with the four suit symbols, one hand pointing to heaven, one to earth, channeling divine energy.',
    symbolism: ['infinity symbol (unlimited potential)', 'four elements', 'red roses (passion)', 'white lilies (purity)'],
    astrological_correspondence: 'Mercury',
    numerological_value: 1,
    element: 'air',
    image_url: '/tarot/major/01-magician.jpg'
  },
  {
    id: 'high-priestess',
    name: 'The High Priestess',
    number: 2,
    arcana: 'major',
    keywords: ['intuition', 'sacred knowledge', 'divine feminine', 'subconscious mind'],
    upright_meaning: 'Intuition, sacred knowledge, divine feminine, subconscious mind. The High Priestess represents inner wisdom and the need to trust your intuition.',
    reversed_meaning: 'Secrets, disconnected from intuition, withdrawal, silence. When reversed, she suggests being cut off from your inner voice.',
    description: 'A serene woman sits between two pillars, holding a scroll of sacred knowledge, with the moon at her feet.',
    symbolism: ['pillars (duality)', 'veil (hidden knowledge)', 'crescent moon (intuition)', 'scroll (sacred wisdom)'],
    astrological_correspondence: 'Moon',
    numerological_value: 2,
    element: 'water',
    image_url: '/tarot/major/02-high-priestess.jpg'
  },
  {
    id: 'empress',
    name: 'The Empress',
    number: 3,
    arcana: 'major',
    keywords: ['femininity', 'beauty', 'nature', 'nurturing', 'abundance'],
    upright_meaning: 'Femininity, beauty, nature, nurturing, abundance. The Empress represents fertility, creativity, and the nurturing aspect of the feminine.',
    reversed_meaning: 'Creative block, dependence on others, smothering, lack of growth. When reversed, The Empress suggests stifled creativity or over-dependence.',
    description: 'A pregnant woman sits in a lush garden, wearing a crown of stars, surrounded by abundance and natural beauty.',
    symbolism: ['twelve stars (zodiac)', 'wheat (fertility)', 'waterfall (emotion)', 'heart-shaped shield (love)'],
    astrological_correspondence: 'Venus',
    numerological_value: 3,
    element: 'earth',
    image_url: '/tarot/major/03-empress.jpg'
  },
  {
    id: 'emperor',
    name: 'The Emperor',
    number: 4,
    arcana: 'major',
    keywords: ['authority', 'father-figure', 'structure', 'control'],
    upright_meaning: 'Authority, father-figure, structure, control. The Emperor represents leadership, stability, and the establishment of order and structure.',
    reversed_meaning: 'Tyranny, rigidity, coldness, domination. When reversed, The Emperor suggests abuse of power or excessive control.',
    description: 'A bearded ruler sits on a stone throne, holding an ankh scepter, representing established power and authority.',
    symbolism: ['stone throne (stability)', 'ankh (life)', 'ram heads (Aries)', 'red robes (passion/power)'],
    astrological_correspondence: 'Aries',
    numerological_value: 4,
    element: 'fire',
    image_url: '/tarot/major/04-emperor.jpg'
  },
  {
    id: 'hierophant',
    name: 'The Hierophant',
    number: 5,
    arcana: 'major',
    keywords: ['spiritual wisdom', 'religious beliefs', 'conformity', 'tradition'],
    upright_meaning: 'Spiritual wisdom, religious beliefs, conformity, tradition. The Hierophant represents conventional wisdom and established spiritual teachings.',
    reversed_meaning: 'Personal beliefs, freedom, challenging the status quo. When reversed, The Hierophant suggests breaking from tradition or questioning authority.',
    description: 'A religious figure sits between two pillars, blessing two acolytes, representing the transmission of spiritual knowledge.',
    symbolism: ['crossed keys (spiritual knowledge)', 'papal crown (authority)', 'two acolytes (teaching)', 'pillars (sacred space)'],
    astrological_correspondence: 'Taurus',
    numerological_value: 5,
    element: 'earth',
    image_url: '/tarot/major/05-hierophant.jpg'
  },
  {
    id: 'lovers',
    name: 'The Lovers',
    number: 6,
    arcana: 'major',
    keywords: ['love', 'harmony', 'relationships', 'choices'],
    upright_meaning: 'Love, harmony, relationships, choices. The Lovers represents deep connections, harmony, and important choices in relationships.',
    reversed_meaning: 'Disharmony, imbalance, misalignment of values. When reversed, The Lovers suggests relationship problems or poor choices.',
    description: 'A man and woman stand beneath an angel, representing divine love and the choice between different paths.',
    symbolism: ['angel (divine blessing)', 'tree of knowledge', 'tree of life', 'mountain (challenges)'],
    astrological_correspondence: 'Gemini',
    numerological_value: 6,
    element: 'air',
    image_url: '/tarot/major/06-lovers.jpg'
  },
  {
    id: 'chariot',
    name: 'The Chariot',
    number: 7,
    arcana: 'major',
    keywords: ['control', 'will power', 'success', 'determination'],
    upright_meaning: 'Control, will power, success, determination. The Chariot represents triumph through maintaining focus and determination.',
    reversed_meaning: 'Lack of control, lack of direction, aggression. When reversed, The Chariot suggests losing control or misdirected energy.',
    description: 'A warrior drives a chariot pulled by two sphinxes, one black and one white, representing the need to control opposing forces.',
    symbolism: ['two sphinxes (opposing forces)', 'star crown (divine guidance)', 'city walls (civilization)', 'armor (protection)'],
    astrological_correspondence: 'Cancer',
    numerological_value: 7,
    element: 'water',
    image_url: '/tarot/major/07-chariot.jpg'
  },
  {
    id: 'strength',
    name: 'Strength',
    number: 8,
    arcana: 'major',
    keywords: ['strength', 'courage', 'persuasion', 'influence'],
    upright_meaning: 'Strength, courage, persuasion, influence. Strength represents inner strength, courage, and the power of gentle persuasion over force.',
    reversed_meaning: 'Self doubt, lack of confidence, lack of self-discipline. When reversed, Strength suggests inner weakness or lack of confidence.',
    description: 'A woman gently closes the mouth of a lion, representing the triumph of love and patience over raw force.',
    symbolism: ['infinity symbol (unlimited potential)', 'lion (raw power)', 'white robes (purity)', 'flower crown (nature)'],
    astrological_correspondence: 'Leo',
    numerological_value: 8,
    element: 'fire',
    image_url: '/tarot/major/08-strength.jpg'
  },
  {
    id: 'hermit',
    name: 'The Hermit',
    number: 9,
    arcana: 'major',
    keywords: ['soul searching', 'seeking truth', 'inner guidance'],
    upright_meaning: 'Soul searching, seeking truth, inner guidance. The Hermit represents the need for introspection and seeking inner wisdom.',
    reversed_meaning: 'Isolation, loneliness, withdrawal. When reversed, The Hermit suggests excessive isolation or refusing guidance.',
    description: 'An old man holds a lantern high, lighting the way for others while standing on a mountain peak.',
    symbolism: ['lantern (inner light)', 'six-pointed star (wisdom)', 'mountain peak (achievement)', 'staff (support)'],
    astrological_correspondence: 'Virgo',
    numerological_value: 9,
    element: 'earth',
    image_url: '/tarot/major/09-hermit.jpg'
  },
  {
    id: 'wheel-of-fortune',
    name: 'Wheel of Fortune',
    number: 10,
    arcana: 'major',
    keywords: ['good luck', 'karma', 'life cycles', 'destiny'],
    upright_meaning: 'Good luck, karma, life cycles, destiny. The Wheel of Fortune represents the cyclical nature of life and karmic lessons.',
    reversed_meaning: 'Bad luck, lack of control, clinging to control. When reversed, it suggests resistance to change or bad luck.',
    description: 'A large wheel with mystical symbols rotates, with figures representing the ups and downs of fortune.',
    symbolism: ['wheel (cycles)', 'sphinx (riddles)', 'snake (knowledge)', 'Anubis (afterlife)'],
    astrological_correspondence: 'Jupiter',
    numerological_value: 10,
    element: 'fire',
    image_url: '/tarot/major/10-wheel-of-fortune.jpg'
  },
  {
    id: 'justice',
    name: 'Justice',
    number: 11,
    arcana: 'major',
    keywords: ['justice', 'fairness', 'truth', 'cause and effect'],
    upright_meaning: 'Justice, fairness, truth, cause and effect. Justice represents the need for fairness and the law of cause and effect.',
    reversed_meaning: 'Unfairness, lack of accountability, dishonesty. When reversed, Justice suggests injustice or avoiding responsibility.',
    description: 'A figure sits on a throne holding scales and a sword, representing balanced judgment and truth.',
    symbolism: ['scales (balance)', 'sword (truth)', 'purple veil (spirituality)', 'square crown (order)'],
    astrological_correspondence: 'Libra',
    numerological_value: 11,
    element: 'air',
    image_url: '/tarot/major/11-justice.jpg'
  },
  {
    id: 'hanged-man',
    name: 'The Hanged Man',
    number: 12,
    arcana: 'major',
    keywords: ['suspension', 'restriction', 'letting go', 'sacrifice'],
    upright_meaning: 'Suspension, restriction, letting go, sacrifice. The Hanged Man represents the need to let go and see things from a new perspective.',
    reversed_meaning: 'Delays, resistance, stalling, indecision. When reversed, it suggests resistance to necessary sacrifice or change.',
    description: 'A man hangs upside down from a tree, appearing peaceful and enlightened despite his position.',
    symbolism: ['halo (enlightenment)', 'tree (life)', 'crossed legs (balance)', 'peaceful expression (acceptance)'],
    astrological_correspondence: 'Neptune',
    numerological_value: 12,
    element: 'water',
    image_url: '/tarot/major/12-hanged-man.jpg'
  },
  {
    id: 'death',
    name: 'Death',
    number: 13,
    arcana: 'major',
    keywords: ['endings', 'beginnings', 'change', 'transformation'],
    upright_meaning: 'Endings, beginnings, change, transformation. Death represents necessary endings that lead to new beginnings and transformation.',
    reversed_meaning: 'Resistance to change, personal transformation, inner purging. When reversed, Death suggests resistance to necessary change.',
    description: 'A skeleton in armor rides a white horse, representing the inevitability of change and transformation.',
    symbolism: ['white horse (purity)', 'black armor (mystery)', 'flag with rose (life after death)', 'rising sun (new beginnings)'],
    astrological_correspondence: 'Scorpio',
    numerological_value: 13,
    element: 'water',
    image_url: '/tarot/major/13-death.jpg'
  },
  {
    id: 'temperance',
    name: 'Temperance',
    number: 14,
    arcana: 'major',
    keywords: ['balance', 'moderation', 'patience', 'purpose'],
    upright_meaning: 'Balance, moderation, patience, purpose. Temperance represents the need for balance and moderation in all things.',
    reversed_meaning: 'Imbalance, excess, self-healing, re-alignment. When reversed, Temperance suggests imbalance or the need for self-healing.',
    description: 'An angel pours water between two cups, representing the flow of life and the mixing of opposites.',
    symbolism: ['angel (divine guidance)', 'water flow (life force)', 'one foot on land/water (balance)', 'triangle (spirit)'],
    astrological_correspondence: 'Sagittarius',
    numerological_value: 14,
    element: 'fire',
    image_url: '/tarot/major/14-temperance.jpg'
  },
  {
    id: 'devil',
    name: 'The Devil',
    number: 15,
    arcana: 'major',
    keywords: ['bondage', 'addiction', 'sexuality', 'materialism'],
    upright_meaning: 'Bondage, addiction, sexuality, materialism. The Devil represents being trapped by material desires or unhealthy attachments.',
    reversed_meaning: 'Releasing limiting beliefs, exploring dark thoughts, detachment. When reversed, The Devil suggests breaking free from bondage.',
    description: 'A horned figure sits above two chained humans, representing bondage to material desires and illusions.',
    symbolism: ['chains (bondage)', 'inverted pentagram (materialism)', 'torch (false light)', 'bat wings (darkness)'],
    astrological_correspondence: 'Capricorn',
    numerological_value: 15,
    element: 'earth',
    image_url: '/tarot/major/15-devil.jpg'
  },
  {
    id: 'tower',
    name: 'The Tower',
    number: 16,
    arcana: 'major',
    keywords: ['sudden change', 'upheaval', 'chaos', 'revelation'],
    upright_meaning: 'Sudden change, upheaval, chaos, revelation. The Tower represents sudden, dramatic change that destroys false foundations.',
    reversed_meaning: 'Personal transformation, fear of change, averting disaster. When reversed, The Tower suggests avoiding or delaying necessary change.',
    description: 'A tower is struck by lightning, with figures falling from it, representing the destruction of false beliefs.',
    symbolism: ['lightning (divine intervention)', 'crown (false ego)', 'falling figures (humbling)', 'flames (purification)'],
    astrological_correspondence: 'Mars',
    numerological_value: 16,
    element: 'fire',
    image_url: '/tarot/major/16-tower.jpg'
  },
  {
    id: 'star',
    name: 'The Star',
    number: 17,
    arcana: 'major',
    keywords: ['hope', 'faith', 'purpose', 'renewal'],
    upright_meaning: 'Hope, faith, purpose, renewal. The Star represents hope, inspiration, and spiritual guidance after a period of darkness.',
    reversed_meaning: 'Lack of faith, despair, self-trust, disconnection. When reversed, The Star suggests loss of hope or faith.',
    description: 'A woman pours water under a starry sky, representing hope and spiritual renewal.',
    symbolism: ['eight stars (hope)', 'water (emotion/spirit)', 'bird (soul)', 'naked figure (authenticity)'],
    astrological_correspondence: 'Aquarius',
    numerological_value: 17,
    element: 'air',
    image_url: '/tarot/major/17-star.jpg'
  },
  {
    id: 'moon',
    name: 'The Moon',
    number: 18,
    arcana: 'major',
    keywords: ['illusion', 'fear', 'anxiety', 'subconscious'],
    upright_meaning: 'Illusion, fear, anxiety, subconscious. The Moon represents illusions, fears, and the need to trust your intuition.',
    reversed_meaning: 'Release of fear, repressed emotion, inner confusion. When reversed, The Moon suggests overcoming fears or illusions.',
    description: 'A full moon shines over a landscape with a path leading into the unknown, flanked by a dog and wolf.',
    symbolism: ['full moon (illusion)', 'dog and wolf (tame/wild nature)', 'crayfish (subconscious)', 'path (journey)'],
    astrological_correspondence: 'Pisces',
    numerological_value: 18,
    element: 'water',
    image_url: '/tarot/major/18-moon.jpg'
  },
  {
    id: 'sun',
    name: 'The Sun',
    number: 19,
    arcana: 'major',
    keywords: ['positivity', 'fun', 'warmth', 'success'],
    upright_meaning: 'Positivity, fun, warmth, success. The Sun represents joy, success, and positive energy in all areas of life.',
    reversed_meaning: 'Inner child, feeling down, overly optimistic. When reversed, The Sun suggests temporary setbacks or need for inner joy.',
    description: 'A bright sun shines over a child riding a white horse, representing pure joy and innocence.',
    symbolism: ['bright sun (consciousness)', 'child (innocence)', 'white horse (purity)', 'sunflowers (happiness)'],
    astrological_correspondence: 'Sun',
    numerological_value: 19,
    element: 'fire',
    image_url: '/tarot/major/19-sun.jpg'
  },
  {
    id: 'judgement',
    name: 'Judgement',
    number: 20,
    arcana: 'major',
    keywords: ['judgement', 'rebirth', 'inner calling', 'absolution'],
    upright_meaning: 'Judgement, rebirth, inner calling, absolution. Judgement represents spiritual awakening and answering a higher calling.',
    reversed_meaning: 'Self-doubt, inner critic, ignoring the call. When reversed, Judgement suggests self-doubt or ignoring your calling.',
    description: 'An angel blows a trumpet as figures rise from their graves, representing spiritual rebirth and awakening.',
    symbolism: ['angel (divine message)', 'trumpet (calling)', 'rising figures (rebirth)', 'cross flag (spirituality)'],
    astrological_correspondence: 'Pluto',
    numerological_value: 20,
    element: 'fire',
    image_url: '/tarot/major/20-judgement.jpg'
  },
  {
    id: 'world',
    name: 'The World',
    number: 21,
    arcana: 'major',
    keywords: ['completion', 'accomplishment', 'travel', 'fulfillment'],
    upright_meaning: 'Completion, accomplishment, travel, fulfillment. The World represents completion of a journey and achievement of goals.',
    reversed_meaning: 'Incomplete goals, lack of closure, stagnation. When reversed, The World suggests unfinished business or lack of closure.',
    description: 'A dancing figure is surrounded by a wreath, with the four elements in the corners, representing completion and wholeness.',
    symbolism: ['wreath (victory)', 'dancing figure (celebration)', 'four elements (wholeness)', 'infinity scarves (eternal)'],
    astrological_correspondence: 'Saturn',
    numerological_value: 21,
    element: 'earth',
    image_url: '/tarot/major/21-world.jpg'
  }
]"